name: ShielD NodeJs

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * 0"
  push:
    branches:
      - main
    paths:
      - hybrid/nodejs/**
      
jobs:
  push:
    name: "shieldid:nodejs_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 14
          - 15
          - 16
          - 17
          - 18
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./shieldid/nodejs
          file: ./shieldid/nodejs/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kanvret12/shieldid:nodejs_${{ matrix.tag }}
